# Generated by Django 5.2.7 on 2025-10-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
        ('users', '0002_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_comics',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='comics.comic'),
        ),
    ]
