# Generated by Django 5.2.7 on 2026-01-10 00:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
        ('users', '0003_profile_favorite_comics'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('read', 'Read'), ('reading', 'Currently Reading'), ('wishlist', 'Want to Read')], default='read', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_read', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_entries', to='comics.comic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'comic')},
            },
        ),
    ]
