# Generated by Django 5.2.7 on 2025-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comics', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comic',
            constraint=models.UniqueConstraint(fields=('title', 'issue_no'), name='unique_title_issue-no'),
        ),
    ]
