# Generated by Django 5.2.7 on 2025-12-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='threadcategory',
            options={'verbose_name': 'Thread Category', 'verbose_name_plural': 'Thread Categories'},
        ),
        migrations.AlterModelOptions(
            name='threadreply',
            options={'verbose_name': 'Thread Reply', 'verbose_name_plural': 'Thread Replies'},
        ),
        migrations.AddField(
            model_name='threadcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
